version: 2.1

orbs:
  bazelisk-orb: promiseofcake/bazelisk-orb@0.3.0

parameters:
  bazel-version:
    default: "1.2.1"
    type: string
  run_build:
    type: boolean
    default: true
  run_output:
    type: boolean
    default: false
  run_release:
    type: boolean
    default: false

jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    environment:
      USE_BAZEL_VERSION: << pipeline.parameters.bazel-version >>
    steps:
      - bazelisk-orb/install
      - checkout
      - run: bazel version
  output:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run: echo "this is an output build"
  pre-validate:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run: echo "this is a validation, should we move forward?"

workflows:
  build:
    when: << pipeline.parameters.run_build >>
    jobs:
      - build
  output:
    when: << pipeline.parameters.run_output >>
    jobs:
      - output
  release:
    when: << pipeline.parameters.run_release >>
    jobs:
      - build
      - pre-validate:
          requires:
            - build
      - validate:
          type: approval
          requires:
            - pre-validate
      - output:
          requires:
            - validate
